version: '3'

services:
  postgres:
    image: postgres:12.3
    ports:
      - "5433:5432"
    environment:
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_DB: booking_db